defaults: &defaults
  host: 0.0.0.3000
  assets_version: 1.0
  appName:  "gomas"

development:
  <<: *defaults
  mensagem: "Olá meu mundo DESENVOLVIMENTO"

test:
  <<: *defaults
  mensagem: "Olá meu mundo TESTES"

production:
  <<: *defaults
  mensagem: "Olá meu mundo PRODUÇÃO"
